### PR TITLE
Use cwd instead of basedir

### PR DESCRIPTION
**Pull request by liveforeverx**

### CODE REVIEW

**Comment by RoadRunnr** [comment]
This change is wrong, it is uncommon for Erlang applications to load stuff from the working directory.

**Comment by thz** [comment]
actually i miss the reasoning why this change appeared to be necessary.

**Comment by liveforeverx** [comment]
@thz without that change, it wasn't possible to build eradius as rebar dependency, because there was a wrong `base_dir`. In our component, we realised, that was used my fork because of this change, and Yury and I wanted to change it.

@RoadRunnr yes, but rebar for that reason always sets right cwd (for dependencies for example), for the reason, that other build components can rely on cwd.

**Comment by RoadRunnr** [comment]
I missed that this is change is in the rebar plugin. That ```rebar_config:get_xconf(Config, base_dir),
``` gets the wrong base dir, looks like a rebar bug to me (should be reported there).

The workaround is fine, sorry for the noise.

**Pull request merged**
