### PR TITLE
Fix warnings for erlang:get_stacktrace/0 in OTP-21+

### PR DESCRIPTION
**Pull request by surik**
Use only last OTP-19, OTP-20 and OTP-21 in Travis

### CODE REVIEW

**Comment by RoadRunnr** [comment]
using a define in erl_opts has problems when you want to overload settings from projects that depends on eradius.

I would prefer to use https://hex.pm/packages/stacktrace_compat.

**Comment by surik** [comment]
@RoadRunnr someone can also lose `{parse_transform, stacktrace_transform}` in `erl_opts` when he is overloading it in top-level application.  I migth have imagined it in wrong way. Could you please show example?

**Comment by surik** [comment]
Seems that since rebar [3.6.1](https://github.com/erlang/rebar3/commit/ea50c24f61e084f0cd258d0bdb1b2117783a7dcb) it is possible to use `add` and `del` for overloading global `erl_opts` see http://www.rebar3.org/docs/configuration#section-overrides

**Comment by vkatsuba** [comment]
PR is outdated and superseded by the use of `stacktrace_compat`

**Pull request closed without merging**
