### PR TITLE
[WiP] add TP_X_NAS_ID attribute

### PR DESCRIPTION
**Pull request by 0xAX**

### CODE REVIEW

**Comment by surik** [comment]
What's the difference with standard `NAS-Identifier`?

**Comment by umatomba** [comment]
Identification for the forwarding request in case of Proxying

**Comment by 0xAX** [comment]
maybe we should choose much clear name for this attribute?

**Comment by umatomba** [comment]
@RoadRunnr 
> I don't think this attribute is needed at all.

why?

> A proxy should not modifiy the NAS-Identifier.

The proxy don't modify anythink in this case. 

> If it does, 

does not

**Comment by umatomba** [comment]
We will use realm based variant in UserName RADIUS attribute

**Pull request closed without merging**
