### PR TITLE
Adding RADIUS dictionary for APC by Schneider Electric

### PR DESCRIPTION
**Pull request by metelik**

### CODE REVIEW

**Comment by vkatsuba** [comment]
What for added `.rebar3/rebar_compiler_erl/source.dag`? The `.rebar3` is not a part of source.

**Review by vkatsuba — CHANGES_REQUESTED** [review]
Please. Delete `.rebar3/rebar_compiler_erl/source.dag`

**Comment by vkatsuba** [comment]
> Done.

Please, squash all commits into one single commit.

**Review by vkatsuba — CHANGES_REQUESTED** [review]
Please, squash all commits into one single commit.

**Comment by metelik** [comment]
> 
> 
> Please, squash all commits into one single commit.

On this branch squashing worked much better ;)

**Comment by vkatsuba** [comment]
LGTM.

**Review by vkatsuba — APPROVED** [review]

**Review by 0xAX — APPROVED** [review]

**Pull request merged**
